require: rubocop-rails

Rails:
  Enabled: true

AllCops:
  TargetRailsVersion: 6.0
  TargetRubyVersion: 2.4
  Include:
    - '**/Rakefile'
    - '**/config.ru'
    - 'app/**/*.rb'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'Gemfile'
  DisplayCopNames: true
  SuggestExtensions: false
  NewCops: enable

Metrics/MethodLength:
  Max: 15

Layout/LineLength:
  Max: 120

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Style/AndOr:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'config/environments/*.rb'
    - 'config/routes.rb'
