version: '2'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      RAILS_ENV: development
      VIRTUAL_HOST: lti13testtool.docker
      REDIS_URL: redis://redis:6379
      DB_USERNAME: postgres
      DB_ADDRESS: postgres
    links:
      - postgres
      - redis
    logging:
      options:
        max-file: '5'
        max-size: 1m
    networks:
      - default
    ports:
      - 8082:80

  redis:
    image: redis:3.2
    logging:
      options:
        max-file: '5'
        max-size: 1m

  postgres:
    image: postgres:9.6.8
    logging:
      options:
        max-file: '5'
        max-size: 1m