version: '2'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      APP_DOMAIN: web
      BUILD_ID: "${BUILD_ID}"
      COVERAGE: 1
      DB_USERNAME: lti13testtooltest
      GERGICH_KEY: "${GERGICH_KEY}"
      GERRIT_PROJECT: "${GERRIT_PROJECT}"
      GERRIT_HOST: "${GERRIT_HOST}"
      GERRIT_BRANCH: "${GERRIT_BRANCH}"
      RAILS_ENV: test
    links:
      - postgres
    volumes:
      - '.git:/usr/src/app/.git'
      - "coverage:/usr/src/app/coverage"
      - ./docker/database.yml:/usr/src/app/config/database.yml

  postgres:
    image: postgres:9.6.8
    environment:
      POSTGRES_USER: lti13testtooltest
      POSTGRES_PASSWORD: lti-13-test-tool-password

volumes:
  coverage: {}
